language: java
jdk: openjdk17
dist: focal

git:
  depth: false
  quiet: true

cache:
  directories:
    - ${HOME}/.m2/repository

branches:
  only:
    - master
    - /feature\/.*/
    - /release\/.*/
    - /support\/.*/

stages:
  - build and test
  - release

before_install: mkdir -p ${HOME}/.m2 && cp -rf _ci/settings.xml ${HOME}/.m2/

jobs:
  include:
    - stage: Build and Test
      name: "Build and Test"
      if: branch = master AND type != pull_request
      install: travis_wait 20 mvn -B -U

    - name: "Release"
      stage: release
      if: commit_message ~= /\[release\]/ AND branch ~= /^(master|SP\/.+|HF\/.+)$/
      before_script: travis_wait bash _ci/cache_artifacts.sh
      script: travis_wait 55 bash _ci/release.sh